### ISSUE TITLE
amule compile fails on snapshot openwrt sdk

### ISSUE THREAD

**Issue by rezad1393** [brvphoenix/SomePackages#1]
I am trying to compile amule for openwrt.
I have download the amule part of your repo and copied it to package folder in the sdk.
then I issue this command "make package/amule/compile V=99 -j1"

but if I just compile it give me errors about boot like this (which I picked from last lines of log on screen)

configure: WARNING: unrecognized options: --without-x

checking for exception-handling... undeterminable
configure: WARNING:
        Cross-compilation detected, so exception handling cannot be tested.
        Note that broken exception handling in your compiler may lead to
        unexpected crashes.

checking for Boost's header version... 1_71
checking for the toolset name used by Boost for arm-openwrt-linux-muslgnueabi-g++... configure: WARNING: could not figure out which toolset name to use for arm-openwrt-linux-muslgnueabi-g++

checking for Boost sources... no
checking boost/system/error_code.hpp usability... no
checking boost/system/error_code.hpp presence... no
checking for boost/system/error_code.hpp... no
configure: error: cannot find boost/system/error_code.hpp

I have installed boost on my archlinux system

and if I put --without-boost
it compiles further but stops with :

install: cannot stat '/home/me/projects/openwrt/snapshot/openwrt-sdk-mvebu-cortexa9_gcc-7.4.0_musl_eabi.Linux-x86_64/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/aMule-2019-08-27/src/webserver/src/amuleweb': No such file or directory

even though I disabled with --disable-webserver

how do I fix this?
is disabling boost a bad thing for the final binary file and performance?

**Comment by brvphoenix** [comment]
The option "--with-boost" should be setted as https://github.com/amule-project/amule/issues/31#issuecomment-189921663.

The binary file of "amuleweb"  will be compiled defaultly in "$(PKG_BUILD_DIR)/src/webserver/src/". I have used the "openwrt-sdk-18.06.4-x86-64_gcc-7.3.0_musl.Linux-x86_64" which can compile the amule successfully.

If you set "--disable-webserver", the line 109 of amule makefile need to be commented: https://github.com/brvphoenix/SomePackages/blob/59bf237356c490b87c5c5e53aa4f71339cf993a0/amule/amule/Makefile#L109

**Comment by rezad1393** [comment]
oh.
I am using snapshot so maybe that is the issue.
or maybe because you are using x86_64 the cross-compile is not that cross at all.

**Comment by brvphoenix** [comment]
@rezad1393 
In fact, I have also tested the snapshot SDK of mvebu-cortexa9 and ath79 using the Ubuntu 18.04 LTS, and I can't 
reproduce the same issue as you have said.

So I think you may need provide the full log by "make package/amule/compile V=s -j1".

Besides, the amule compiled by the latested snapshot SDK of mvebu-cortexa9 can be downloaded [here](https://github.com/brvphoenix/SomePackages/files/3737046/aMule_Packages.zip).

**Comment by rezad1393** [comment]
oh
did you just upload that for me?
thank you.

I have archlinux installed so maybe that's the cause?
about the log, I have included the last lines that show the error because the whole log it too big (if I can find it).

also I have removed the development folder and now use amule from a chroot inside openwrt installed in a  debian chroot.
